### ISSUE TITLE
does it need serverOutFilePath: 

### ISSUE THREAD

**Issue by joloman2** [Jaskowicz1/Factorio-Discord-Relay#6]
hi im trying to setup a bot but it need me to put in the serverOutFilePath: <> but im runing on a hosting is there annyway around it and if not how can i get it to work

Regards

Joloman2

**Comment by Jaskowicz1** [comment]
There isn't another way around it, sorry. The bot requires the server.out file so it can see the console, otherwise it has no idea what's going on. This is so you don't need to mod the game and you can still have achievements. As of right now, I don't know if there's a possible way you can get it running (if you have access to custom start-up arguments), you could type a script and get the server to run the script which will open the relay and the server. Apart from that, I'm not too sure how to help get this running without a mod, and even then I'd need to make a separate thing so you can run it as a mod.

I would see about trying to let the bot read the server.out path, over the internet (so you can give it FTP username and password so it can live read the file) but that would be delayed from real time, it would still work though but also possibly cause issues.

TDLR: I'll see what I can do to let you run this on your host.

**Comment by Jaskowicz1** [comment]
Looking into this further shows that I can make it so you can use this without the server.out file (if I allow it, that is), however, you won't be able to see any messages or anything from the server. You'll only be able to send messages to the server from discord.

Question, are you able to run this on your hosting?

**Comment by joloman2** [comment]
oke i can give it an ftp user name and pwrd but what do i put in to the file path 
i dont think i can run it on the hosting need to ask support for that maybe i a make a lua script to run the file but im not sure

**Comment by Jaskowicz1** [comment]
Okay, well the FTP route isn't possible (and probably won't be) and currently you can't put anything into the serverOutFilePath as you aren't able to reach the file (as well as you can't run the bot).

**Comment by joloman2** [comment]
i used this to fix it https://wiki.archlinux.org/title/CurlFtpFS

**Comment by joloman2** [comment]
and a linux macheen to mount it as al location and it can just see the file
